import './globals.css';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { GlobalState } from '@/context/UserContext';
 
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Digital Sathi: Web Development Services',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
  <html lang="en">
    <body className={inter.className}>     
        <ToastContainer/>
        <GlobalState>
          <div>
            {children}
          </div>
        </GlobalState>
     </body>
  </html> 
  )
}
